package net.bobs.own.db.h2.db;

import java.util.ArrayList;

/**
 * List the auto generated keys for an executed SQL statement.
 * 
 * @author Robert Anderson
 *
 */
public class AutoGeneratedKeysList extends ArrayList<Integer> {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6336322857687748090L;
	private ArrayList<Integer> keysList = new ArrayList<Integer>();
	
	public AutoGeneratedKeysList() {
		keysList = new ArrayList<Integer>();
	}
	

	public void addKey(int key) {
		keysList.add(new Integer(key));
	}
	
	public int getKey(int index) {
		int key = keysList.get(index).intValue();
		return key;
	}
	
	public int size() {
		return this.keysList.size();
	}
	
}
