package net.bobs.own.db.h2.db;

public class AutoGeneratedKeysResult {

	int returnCode = -1;
	AutoGeneratedKeysList keysList = null;
	
	public AutoGeneratedKeysResult(int returnCode) {
		this.returnCode = returnCode;	
		keysList = new AutoGeneratedKeysList();
	}
	
	public int getReturnCode() {
		return this.returnCode;
	}
	
	public AutoGeneratedKeysList getAutoGeneratedKeys() {
		return keysList;
	}
}
